package net.pieroxy.ua.detection;
import java.io.*;
import java.util.*;
/**
* Describes a country.
*/
public enum Country {
    /** Unknown */UNKNOWN("Unknown"),
    /** Ascension Island */AC("Ascension Island"),
    /** ANDORRA */AD("ANDORRA"),
    /** UNITED ARAB EMIRATES */AE("UNITED ARAB EMIRATES"),
    /** AFGHANISTAN */AF("AFGHANISTAN"),
    /** ANTIGUA AND BARBUDA */AG("ANTIGUA AND BARBUDA"),
    /** ANGUILLA */AI("ANGUILLA"),
    /** ALBANIA */AL("ALBANIA"),
    /** ARMENIA */AM("ARMENIA"),
    /** Netherlands Antilles */AN("Netherlands Antilles"),
    /** ANGOLA */AO("ANGOLA"),
    /** African Regional Industrial Property Organization */AP("African Regional Industrial Property Organization"),
    /** ANTARCTICA */AQ("ANTARCTICA"),
    /** ARGENTINA */AR("ARGENTINA"),
    /** AMERICAN SAMOA */AS("AMERICAN SAMOA"),
    /** AUSTRIA */AT("AUSTRIA"),
    /** AUSTRALIA */AU("AUSTRALIA"),
    /** ARUBA */AW("ARUBA"),
    /** ALAND ISLANDS */AX("ALAND ISLANDS"),
    /** AZERBAIJAN */AZ("AZERBAIJAN"),
    /** BOSNIA AND HERZEGOVINA */BA("BOSNIA AND HERZEGOVINA"),
    /** BARBADOS */BB("BARBADOS"),
    /** BANGLADESH */BD("BANGLADESH"),
    /** BELGIUM */BE("BELGIUM"),
    /** BURKINA FASO */BF("BURKINA FASO"),
    /** BULGARIA */BG("BULGARIA"),
    /** BAHRAIN */BH("BAHRAIN"),
    /** BURUNDI */BI("BURUNDI"),
    /** BENIN */BJ("BENIN"),
    /** SAINT BARTHELEMY */BL("SAINT BARTHELEMY"),
    /** BERMUDA */BM("BERMUDA"),
    /** BRUNEI DARUSSALAM */BN("BRUNEI DARUSSALAM"),
    /** BOLIVIA, PLURINATIONAL STATE OF */BO("BOLIVIA, PLURINATIONAL STATE OF"),
    /** BONAIRE, SINT EUSTATIUS AND SABA */BQ("BONAIRE, SINT EUSTATIUS AND SABA"),
    /** BRAZIL */BR("BRAZIL"),
    /** BAHAMAS */BS("BAHAMAS"),
    /** BHUTAN */BT("BHUTAN"),
    /** Burma */BU("Burma"),
    /** BOUVET ISLAND */BV("BOUVET ISLAND"),
    /** BOTSWANA */BW("BOTSWANA"),
    /** Benelux Trademarks and Designs Office */BX("Benelux Trademarks and Designs Office"),
    /** BELARUS */BY("BELARUS"),
    /** BELIZE */BZ("BELIZE"),
    /** CANADA */CA("CANADA"),
    /** COCOS (KEELING) ISLANDS */CC("COCOS (KEELING) ISLANDS"),
    /** CONGO, THE DEMOCRATIC REPUBLIC OF THE */CD("CONGO, THE DEMOCRATIC REPUBLIC OF THE"),
    /** CENTRAL AFRICAN REPUBLIC */CF("CENTRAL AFRICAN REPUBLIC"),
    /** CONGO */CG("CONGO"),
    /** SWITZERLAND */CH("SWITZERLAND"),
    /** COTE D'IVOIRE */CI("COTE D'IVOIRE"),
    /** COOK ISLANDS */CK("COOK ISLANDS"),
    /** CHILE */CL("CHILE"),
    /** CAMEROON */CM("CAMEROON"),
    /** CHINA */CN("CHINA"),
    /** COLOMBIA */CO("COLOMBIA"),
    /** Clipperton Island */CP("Clipperton Island"),
    /** COSTA RICA */CR("COSTA RICA"),
    /** SERBIA AND MONTENEGRO */CS("SERBIA AND MONTENEGRO"),
    /** CUBA */CU("CUBA"),
    /** CAPE VERDE */CV("CAPE VERDE"),
    /** Curacao */CW("Curacao"),
    /** CHRISTMAS ISLAND */CX("CHRISTMAS ISLAND"),
    /** CYPRUS */CY("CYPRUS"),
    /** CZECH REPUBLIC */CZ("CZECH REPUBLIC"),
    /** GERMANY */DE("GERMANY"),
    /** Diego Garcia */DG("Diego Garcia"),
    /** DJIBOUTI */DJ("DJIBOUTI"),
    /** DENMARK */DK("DENMARK"),
    /** DOMINICA */DM("DOMINICA"),
    /** DOMINICAN REPUBLIC */DO("DOMINICAN REPUBLIC"),
    /** Benin */DY("Benin"),
    /** ALGERIA */DZ("ALGERIA"),
    /** Ceuta, Melilla */EA("Ceuta, Melilla"),
    /** ECUADOR */EC("ECUADOR"),
    /** ESTONIA */EE("ESTONIA"),
    /** Union of Countries under the European Community Patent Convention */EF("Union of Countries under the European Community Patent Convention"),
    /** EGYPT */EG("EGYPT"),
    /** WESTERN SAHARA */EH("WESTERN SAHARA"),
    /** European Trademark Office */EM("European Trademark Office"),
    /** European Patent Organization */EP("European Patent Organization"),
    /** ERITREA */ER("ERITREA"),
    /** SPAIN */ES("SPAIN"),
    /** ETHIOPIA */ET("ETHIOPIA"),
    /** European Union */EU("European Union"),
    /** Eurasian Patent Organization */EV("Eurasian Patent Organization"),
    /** Estonia */EW("Estonia"),
    /** FINLAND */FI("FINLAND"),
    /** FIJI */FJ("FIJI"),
    /** FALKLAND ISLANDS (MALVINAS) */FK("FALKLAND ISLANDS (MALVINAS)"),
    /** Liechtenstein */FL("Liechtenstein"),
    /** MICRONESIA, FEDERATED STATES OF */FM("MICRONESIA, FEDERATED STATES OF"),
    /** FAROE ISLANDS */FO("FAROE ISLANDS"),
    /** FRANCE */FR("FRANCE"),
    /** France, Metropolitan */FX("France, Metropolitan"),
    /** GABON */GA("GABON"),
    /** UNITED KINGDOM */GB("UNITED KINGDOM"),
    /** Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC) */GC("Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)"),
    /** GRENADA */GD("GRENADA"),
    /** GEORGIA */GE("GEORGIA"),
    /** FRENCH GUIANA */GF("FRENCH GUIANA"),
    /** GUERNSEY */GG("GUERNSEY"),
    /** GHANA */GH("GHANA"),
    /** GIBRALTAR */GI("GIBRALTAR"),
    /** GREENLAND */GL("GREENLAND"),
    /** GAMBIA */GM("GAMBIA"),
    /** GUINEA */GN("GUINEA"),
    /** GUADELOUPE */GP("GUADELOUPE"),
    /** EQUATORIAL GUINEA */GQ("EQUATORIAL GUINEA"),
    /** GREECE */GR("GREECE"),
    /** SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS */GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
    /** GUATEMALA */GT("GUATEMALA"),
    /** GUAM */GU("GUAM"),
    /** GUINEA-BISSAU */GW("GUINEA-BISSAU"),
    /** GUYANA */GY("GUYANA"),
    /** HONG KONG */HK("HONG KONG"),
    /** HEARD ISLAND AND MCDONALD ISLANDS */HM("HEARD ISLAND AND MCDONALD ISLANDS"),
    /** HONDURAS */HN("HONDURAS"),
    /** CROATIA */HR("CROATIA"),
    /** HAITI */HT("HAITI"),
    /** HUNGARY */HU("HUNGARY"),
    /** International Bureau of WIPO */IB("International Bureau of WIPO"),
    /** Canary Islands */IC("Canary Islands"),
    /** INDONESIA */ID("INDONESIA"),
    /** IRELAND */IE("IRELAND"),
    /** ISRAEL */IL("ISRAEL"),
    /** ISLE OF MAN */IM("ISLE OF MAN"),
    /** INDIA */IN("INDIA"),
    /** BRITISH INDIAN OCEAN TERRITORY */IO("BRITISH INDIAN OCEAN TERRITORY"),
    /** IRAQ */IQ("IRAQ"),
    /** IRAN, ISLAMIC REPUBLIC OF */IR("IRAN, ISLAMIC REPUBLIC OF"),
    /** ICELAND */IS("ICELAND"),
    /** ITALY */IT("ITALY"),
    /** Jamaica */JA("Jamaica"),
    /** JERSEY */JE("JERSEY"),
    /** JAMAICA */JM("JAMAICA"),
    /** JORDAN */JO("JORDAN"),
    /** JAPAN */JP("JAPAN"),
    /** KENYA */KE("KENYA"),
    /** KYRGYZSTAN */KG("KYRGYZSTAN"),
    /** CAMBODIA */KH("CAMBODIA"),
    /** KIRIBATI */KI("KIRIBATI"),
    /** COMOROS */KM("COMOROS"),
    /** SAINT KITTS AND NEVIS */KN("SAINT KITTS AND NEVIS"),
    /** KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF */KP("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
    /** KOREA, REPUBLIC OF */KR("KOREA, REPUBLIC OF"),
    /** KUWAIT */KW("KUWAIT"),
    /** CAYMAN ISLANDS */KY("CAYMAN ISLANDS"),
    /** KAZAKHSTAN */KZ("KAZAKHSTAN"),
    /** LAO PEOPLE'S DEMOCRATIC REPUBLIC */LA("LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
    /** LEBANON */LB("LEBANON"),
    /** SAINT LUCIA */LC("SAINT LUCIA"),
    /** Libya Fezzan */LF("Libya Fezzan"),
    /** LIECHTENSTEIN */LI("LIECHTENSTEIN"),
    /** SRI LANKA */LK("SRI LANKA"),
    /** LIBERIA */LR("LIBERIA"),
    /** LESOTHO */LS("LESOTHO"),
    /** LITHUANIA */LT("LITHUANIA"),
    /** LUXEMBOURG */LU("LUXEMBOURG"),
    /** LATVIA */LV("LATVIA"),
    /** LIBYA */LY("LIBYA"),
    /** MOROCCO */MA("MOROCCO"),
    /** MONACO */MC("MONACO"),
    /** MOLDOVA, REPUBLIC OF */MD("MOLDOVA, REPUBLIC OF"),
    /** MONTENEGRO */ME("MONTENEGRO"),
    /** SAINT MARTIN (FRENCH PART) */MF("SAINT MARTIN (FRENCH PART)"),
    /** MADAGASCAR */MG("MADAGASCAR"),
    /** MARSHALL ISLANDS */MH("MARSHALL ISLANDS"),
    /** MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF */MK("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
    /** MALI */ML("MALI"),
    /** MYANMAR */MM("MYANMAR"),
    /** MONGOLIA */MN("MONGOLIA"),
    /** MACAO */MO("MACAO"),
    /** NORTHERN MARIANA ISLANDS */MP("NORTHERN MARIANA ISLANDS"),
    /** MARTINIQUE */MQ("MARTINIQUE"),
    /** MAURITANIA */MR("MAURITANIA"),
    /** MONTSERRAT */MS("MONTSERRAT"),
    /** MALTA */MT("MALTA"),
    /** MAURITIUS */MU("MAURITIUS"),
    /** MALDIVES */MV("MALDIVES"),
    /** MALAWI */MW("MALAWI"),
    /** MEXICO */MX("MEXICO"),
    /** MALAYSIA */MY("MALAYSIA"),
    /** MOZAMBIQUE */MZ("MOZAMBIQUE"),
    /** NAMIBIA */NA("NAMIBIA"),
    /** NEW CALEDONIA */NC("NEW CALEDONIA"),
    /** NIGER */NE("NIGER"),
    /** NORFOLK ISLAND */NF("NORFOLK ISLAND"),
    /** NIGERIA */NG("NIGERIA"),
    /** NICARAGUA */NI("NICARAGUA"),
    /** NETHERLANDS */NL("NETHERLANDS"),
    /** NORWAY */NO("NORWAY"),
    /** NEPAL */NP("NEPAL"),
    /** NAURU */NR("NAURU"),
    /** Neutral Zone */NT("Neutral Zone"),
    /** NIUE */NU("NIUE"),
    /** NEW ZEALAND */NZ("NEW ZEALAND"),
    /** African Intellectual Property Organization */OA("African Intellectual Property Organization"),
    /** OMAN */OM("OMAN"),
    /** PANAMA */PA("PANAMA"),
    /** PERU */PE("PERU"),
    /** FRENCH POLYNESIA */PF("FRENCH POLYNESIA"),
    /** PAPUA NEW GUINEA */PG("PAPUA NEW GUINEA"),
    /** PHILIPPINES */PH("PHILIPPINES"),
    /** Philippines */PI("Philippines"),
    /** PAKISTAN */PK("PAKISTAN"),
    /** POLAND */PL("POLAND"),
    /** SAINT PIERRE AND MIQUELON */PM("SAINT PIERRE AND MIQUELON"),
    /** PITCAIRN */PN("PITCAIRN"),
    /** PUERTO RICO */PR("PUERTO RICO"),
    /** PALESTINIAN, STATE OF */PS("PALESTINIAN, STATE OF"),
    /** PORTUGAL */PT("PORTUGAL"),
    /** PALAU */PW("PALAU"),
    /** PARAGUAY */PY("PARAGUAY"),
    /** QATAR */QA("QATAR"),
    /** Argentina */RA("Argentina"),
    /** Bolivia [cf. Botswana: identical code element] */RB("Bolivia [cf. Botswana: identical code element]"),
    /** China */RC("China"),
    /** Reunion */RE("Reunion"),
    /** Haiti */RH("Haiti"),
    /** Indonesia */RI("Indonesia"),
    /** Lebanon */RL("Lebanon"),
    /** Madagascar */RM("Madagascar"),
    /** Niger */RN("Niger"),
    /** ROMANIA */RO("ROMANIA"),
    /** Philippines */RP("Philippines"),
    /** SERBIA */RS("SERBIA"),
    /** RUSSIAN FEDERATION */RU("RUSSIAN FEDERATION"),
    /** RWANDA */RW("RWANDA"),
    /** SAUDI ARABIA */SA("SAUDI ARABIA"),
    /** SOLOMON ISLANDS */SB("SOLOMON ISLANDS"),
    /** SEYCHELLES */SC("SEYCHELLES"),
    /** SUDAN */SD("SUDAN"),
    /** SWEDEN */SE("SWEDEN"),
    /** Finland */SF("Finland"),
    /** SINGAPORE */SG("SINGAPORE"),
    /** SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA */SH("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"),
    /** SLOVENIA */SI("SLOVENIA"),
    /** SVALBARD AND JAN MAYEN */SJ("SVALBARD AND JAN MAYEN"),
    /** SLOVAKIA */SK("SLOVAKIA"),
    /** SIERRA LEONE */SL("SIERRA LEONE"),
    /** SAN MARINO */SM("SAN MARINO"),
    /** SENEGAL */SN("SENEGAL"),
    /** SOMALIA */SO("SOMALIA"),
    /** SURINAME */SR("SURINAME"),
    /** SOUTH SUDAN */SS("SOUTH SUDAN"),
    /** SAO TOME AND PRINCIPE */ST("SAO TOME AND PRINCIPE"),
    /** USSR */SU("USSR"),
    /** EL SALVADOR */SV("EL SALVADOR"),
    /** SINT MAARTEN (DUTCH PART) */SX("SINT MAARTEN (DUTCH PART)"),
    /** SYRIAN ARAB REPUBLIC */SY("SYRIAN ARAB REPUBLIC"),
    /** SWAZILAND */SZ("SWAZILAND"),
    /** Tristan da Cunha */TA("Tristan da Cunha"),
    /** TURKS AND CAICOS ISLANDS */TC("TURKS AND CAICOS ISLANDS"),
    /** CHAD */TD("CHAD"),
    /** FRENCH SOUTHERN TERRITORIES */TF("FRENCH SOUTHERN TERRITORIES"),
    /** TOGO */TG("TOGO"),
    /** THAILAND */TH("THAILAND"),
    /** TAJIKISTAN */TJ("TAJIKISTAN"),
    /** TOKELAU */TK("TOKELAU"),
    /** TIMOR-LESTE */TL("TIMOR-LESTE"),
    /** TURKMENISTAN */TM("TURKMENISTAN"),
    /** TUNISIA */TN("TUNISIA"),
    /** TONGA */TO("TONGA"),
    /** East Timor */TP("East Timor"),
    /** TURKEY */TR("TURKEY"),
    /** TRINIDAD AND TOBAGO */TT("TRINIDAD AND TOBAGO"),
    /** TUVALU */TV("TUVALU"),
    /** TAIWAN, PROVINCE OF CHINA */TW("TAIWAN, PROVINCE OF CHINA"),
    /** TANZANIA, UNITED REPUBLIC OF */TZ("TANZANIA, UNITED REPUBLIC OF"),
    /** UKRAINE */UA("UKRAINE"),
    /** UGANDA */UG("UGANDA"),
    /** United Kingdom */UK("United Kingdom"),
    /** UNITED STATES MINOR OUTLYING ISLANDS */UM("UNITED STATES MINOR OUTLYING ISLANDS"),
    /** UNITED STATES */US("UNITED STATES"),
    /** URUGUAY */UY("URUGUAY"),
    /** UZBEKISTAN */UZ("UZBEKISTAN"),
    /** HOLY SEE (VATICAN CITY STATE) */VA("HOLY SEE (VATICAN CITY STATE)"),
    /** SAINT VINCENT AND THE GRENADINES */VC("SAINT VINCENT AND THE GRENADINES"),
    /** VENEZUELA, BOLIVARIAN REPUBLIC */VE("VENEZUELA, BOLIVARIAN REPUBLIC"),
    /** VIRGIN ISLANDS, BRITISH */VG("VIRGIN ISLANDS, BRITISH"),
    /** VIRGIN ISLANDS, U.S. */VI("VIRGIN ISLANDS, U.S."),
    /** VIET NAM */VN("VIET NAM"),
    /** VANUATU */VU("VANUATU"),
    /** WALLIS AND FUTUNA */WF("WALLIS AND FUTUNA"),
    /** Grenada */WG("Grenada"),
    /** Saint Lucia */WL("Saint Lucia"),
    /** World Intellectual Property Organization */WO("World Intellectual Property Organization"),
    /** SAMOA */WS("SAMOA"),
    /** Saint Vincent */WV("Saint Vincent"),
    /** YEMEN */YE("YEMEN"),
    /** MAYOTTE */YT("MAYOTTE"),
    /** Yugoslavia */YU("Yugoslavia"),
    /** Venezuela */YV("Venezuela"),
    /** SOUTH AFRICA */ZA("SOUTH AFRICA"),
    /** ZAMBIA */ZM("ZAMBIA"),
    /** Zaire */ZR("Zaire"),
    /** ZIMBABWE */ZW("ZIMBABWE");

    private String label;
    Country(String _label) {
        label = _label;
    }
    public String getLabel() {
        return label;
    }

}