package net.pieroxy.ua.detection;
import java.io.*;
import java.util.*;
/**
* Describes a language.
*/
public enum Language {
    /** Unknown */ UNKNOWN("Unknown"),
    /** Afar */ AA("Afar"),
    /** Abkhazian */ AB("Abkhazian"),
    /** Afrikaans */ AF("Afrikaans"),
    /** Akan */ AK("Akan"),
    /** Albanian */ SQ("Albanian"),
    /** Amharic */ AM("Amharic"),
    /** Arabic */ AR("Arabic"),
    /** Aragonese */ AN("Aragonese"),

    /** Assamese */ AS("Assamese"),
    /** Avaric */ AV("Avaric"),
    /** Avestan */ AE("Avestan"),
    /** Aymara */ AY("Aymara"),
    /** Azerbaijani */ AZ("Azerbaijani"),
    /** Bashkir */ BA("Bashkir"),
    /** Bambara */ BM("Bambara"),

    /** Belarusian */ BE("Belarusian"),
    /** Bengali */ BN("Bengali"),
    /** Bihari languages */ BH("Bihari languages"),
    /** Bislama */ BI("Bislama"),
    /** Tibetan */ BO("Tibetan"),
    /** Bosnian */ BS("Bosnian"),
    /** Breton */ BR("Breton"),
    /** Bulgarian */ BG("Bulgarian"),

    /** Catalan; Valencian */ CA("Catalan; Valencian"),

    /** Chamorro */ CH("Chamorro"),
    /** Chechen */ CE("Chechen"),

    /** Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic */ CU("Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
    /** Chuvash */ CV("Chuvash"),
    /** Cornish */ KW("Cornish"),
    /** Corsican */ CO("Corsican"),
    /** Cree */ CR("Cree"),
    /** Welsh */ CY("Welsh"),
    /** Czech */ CS("Czech"),
    /** Danish */ DA("Danish"),
    /** German */ DE("German"),
    /** Divehi; Dhivehi; Maldivian */ DV("Divehi; Dhivehi; Maldivian"),

    /** Dzongkha */ DZ("Dzongkha"),
    /** Greek, Modern (1453-) */ EL("Greek, Modern (1453-)"),
    /** English */ EN("English"),
    /** Esperanto */ EO("Esperanto"),
    /** Estonian */ ET("Estonian"),
    /** Basque */ EU("Basque"),
    /** Ewe */ EE("Ewe"),
    /** Faroese */ FO("Faroese"),
    /** Persian */ FA("Persian"),
    /** Fijian */ FJ("Fijian"),
    /** Finnish */ FI("Finnish"),
    /** French */ FR("French"),

    /** Western Frisian */ FY("Western Frisian"),
    /** Fulah */ FF("Fulah"),


    /** Gaelic; Scottish Gaelic */ GD("Gaelic; Scottish Gaelic"),
    /** Irish */ GA("Irish"),
    /** Galician */ GL("Galician"),
    /** Manx */ GV("Manx"),

    /** Guarani */ GN("Guarani"),
    /** Gujarati */ GU("Gujarati"),
    /** Haitian; Haitian Creole */ HT("Haitian; Haitian Creole"),
    /** Hausa */ HA("Hausa"),
    /** Hebrew */ HE("Hebrew"),
    /** Herero */ HZ("Herero"),
    /** Hindi */ HI("Hindi"),
    /** Hiri Motu */ HO("Hiri Motu"),
    /** Croatian */ HR("Croatian"),
    /** Hungarian */ HU("Hungarian"),
    /** Armenian */ HY("Armenian"),
    /** Igbo */ IG("Igbo"),
    /** Icelandic */ IS("Icelandic"),
    /** Ido */ IO("Ido"),
    /** Sichuan Yi; Nuosu */ II("Sichuan Yi; Nuosu"),
    /** Inuktitut */ IU("Inuktitut"),
    /** Interlingue; Occidental */ IE("Interlingue; Occidental"),
    /** Interlingua (International Auxiliary Language Association) */ IA("Interlingua (International Auxiliary Language Association)"),
    /** Indonesian */ ID("Indonesian"),
    /** Inupiaq */ IK("Inupiaq"),
    /** Indonesian */ IN("Indonesian"),
    /** Hebrew */ IW("Hebrew"),

    /** Italian */ IT("Italian"),
    /** Yiddish */ JI("Yiddish"),
    /** Javanese */ JV("Javanese"),
    /** Japanese */ JA("Japanese"),
    /** Kalaallisut; Greenlandic */ KL("Kalaallisut; Greenlandic"),
    /** Kannada */ KN("Kannada"),
    /** Kashmiri */ KS("Kashmiri"),
    /** Georgian */ KA("Georgian"),
    /** Kanuri */ KR("Kanuri"),
    /** Kazakh */ KK("Kazakh"),
    /** Central Khmer */ KM("Central Khmer"),
    /** Kikuyu; Gikuyu */ KI("Kikuyu; Gikuyu"),
    /** Kinyarwanda */ RW("Kinyarwanda"),
    /** Kirghiz; Kyrgyz */ KY("Kirghiz; Kyrgyz"),
    /** Komi */ KV("Komi"),
    /** Kongo */ KG("Kongo"),
    /** Korean */ KO("Korean"),
    /** Kuanyama; Kwanyama */ KJ("Kuanyama; Kwanyama"),
    /** Kurdish */ KU("Kurdish"),
    /** Lao */ LO("Lao"),
    /** Latin */ LA("Latin"),
    /** Latvian */ LV("Latvian"),
    /** Limburgan; Limburger; Limburgish */ LI("Limburgan; Limburger; Limburgish"),
    /** Lingala */ LN("Lingala"),
    /** Lithuanian */ LT("Lithuanian"),
    /** Luxembourgish; Letzeburgesch */ LB("Luxembourgish; Letzeburgesch"),
    /** Luba-Katanga */ LU("Luba-Katanga"),
    /** Ganda */ LG("Ganda"),

    /** Marshallese */ MH("Marshallese"),
    /** Malayalam */ ML("Malayalam"),
    /** Maori */ MI("Maori"),
    /** Marathi */ MR("Marathi"),
    /** Malay */ MS("Malay"),
    /** Macedonian */ MK("Macedonian"),
    /** Malagasy */ MG("Malagasy"),
    /** Maltese */ MT("Maltese"),
    /** Mongolian */ MN("Mongolian"),


    /** Burmese */ MY("Burmese"),
    /** Nauru */ NA("Nauru"),
    /** Navajo; Navaho */ NV("Navajo; Navaho"),
    /** Ndebele, South; South Ndebele */ NR("Ndebele, South; South Ndebele"),
    /** Ndebele, North; North Ndebele */ ND("Ndebele, North; North Ndebele"),
    /** Ndonga */ NG("Ndonga"),
    /** Nepali */ NE("Nepali"),
    /** Dutch; Flemish */ NL("Dutch; Flemish"),
    /** Norwegian Nynorsk; Nynorsk, Norwegian */ NN("Norwegian Nynorsk; Nynorsk, Norwegian"),
    /** Bokmal, Norwegian; Norwegian Bokmal */ NB("Bokmal, Norwegian; Norwegian Bokmal"),
    /** Norwegian */ NO("Norwegian"),
    /** Chichewa; Chewa; Nyanja */ NY("Chichewa; Chewa; Nyanja"),
    /** Occitan (post 1500) */ OC("Occitan (post 1500)"),
    /** Ojibwa */ OJ("Ojibwa"),
    /** Oriya */ OR("Oriya"),
    /** Oromo */ OM("Oromo"),
    /** Ossetian; Ossetic */ OS("Ossetian; Ossetic"),
    /** Panjabi; Punjabi */ PA("Panjabi; Punjabi"),

    /** Pali */ PI("Pali"),
    /** Polish */ PL("Polish"),
    /** Portuguese */ PT("Portuguese"),
    /** Pushto; Pashto */ PS("Pushto; Pashto"),
    /** Quechua */ QU("Quechua"),
    /** Romansh */ RM("Romansh"),

    /** Romanian; Moldavian; Moldovan */ RO("Romanian; Moldavian; Moldovan"),
    /** Rundi */ RN("Rundi"),
    /** Russian */ RU("Russian"),
    /** Sango */ SG("Sango"),
    /** Sanskrit */ SA("Sanskrit"),
    /** Sinhala; Sinhalese */ SI("Sinhala; Sinhalese"),

    /** Slovak */ SK("Slovak"),
    /** Slovenian */ SL("Slovenian"),
    /** Northern Sami */ SE("Northern Sami"),
    /** Samoan */ SM("Samoan"),
    /** Shona */ SN("Shona"),
    /** Sindhi */ SD("Sindhi"),
    /** Somali */ SO("Somali"),
    /** Sotho, Southern */ ST("Sotho, Southern"),
    /** Spanish; Castilian */ ES("Spanish; Castilian"),
    /** Sardinian */ SC("Sardinian"),
    /** Serbian */ SR("Serbian"),
    /** Swati */ SS("Swati"),
    /** Sundanese */ SU("Sundanese"),
    /** Swahili */ SW("Swahili"),
    /** Swedish */ SV("Swedish"),
    /** Tahitian */ TY("Tahitian"),
    /** Tamil */ TA("Tamil"),
    /** Tatar */ TT("Tatar"),
    /** Telugu */ TE("Telugu"),
    /** Tajik */ TG("Tajik"),
    /** Tagalog */ TL("Tagalog"),
    /** Thai */ TH("Thai"),

    /** Tigrinya */ TI("Tigrinya"),
    /** Tonga (Tonga Islands) */ TO("Tonga (Tonga Islands)"),
    /** Tswana */ TN("Tswana"),
    /** Tsonga */ TS("Tsonga"),
    /** Turkmen */ TK("Turkmen"),
    /** Turkish */ TR("Turkish"),
    /** Twi */ TW("Twi"),
    /** Uighur; Uyghur */ UG("Uighur; Uyghur"),
    /** Ukrainian */ UK("Ukrainian"),
    /** Urdu */ UR("Urdu"),
    /** Uzbek */ UZ("Uzbek"),
    /** Venda */ VE("Venda"),
    /** Vietnamese */ VI("Vietnamese"),
    /** Volapuk */ VO("Volapuk"),

    /** Walloon */ WA("Walloon"),
    /** Wolof */ WO("Wolof"),
    /** Xhosa */ XH("Xhosa"),
    /** Yiddish */ YI("Yiddish"),
    /** Yoruba */ YO("Yoruba"),
    /** Zhuang; Chuang */ ZA("Zhuang; Chuang"),
    /** Chinese */ ZH("Chinese"),
    /** Zulu */ ZU("Zulu");

    private String label;
    Language(String _label) {
        label = _label;
    }
    public String getLabel() {
        return label;
    }

}