package net.pieroxy.ua.detection;
import java.io.*;
import java.util.*;
public enum Country {  UNKNOWN("Unknown"),
                       AC("Ascension Island"),
                       AD("ANDORRA"),
                       AE("UNITED ARAB EMIRATES"),
                       AF("AFGHANISTAN"),
                       AG("ANTIGUA AND BARBUDA"),
                       AI("ANGUILLA"),
                       AL("ALBANIA"),
                       AM("ARMENIA"),
                       AN("Netherlands Antilles"),
                       AO("ANGOLA"),
                       AP("African Regional Industrial Property Organization"),
                       AQ("ANTARCTICA"),
                       AR("ARGENTINA"),
                       AS("AMERICAN SAMOA"),
                       AT("AUSTRIA"),
                       AU("AUSTRALIA"),
                       AW("ARUBA"),
                       AX("ALAND ISLANDS"),
                       AZ("AZERBAIJAN"),
                       BA("BOSNIA AND HERZEGOVINA"),
                       BB("BARBADOS"),
                       BD("BANGLADESH"),
                       BE("BELGIUM"),
                       BF("BURKINA FASO"),
                       BG("BULGARIA"),
                       BH("BAHRAIN"),
                       BI("BURUNDI"),
                       BJ("BENIN"),
                       BL("SAINT BARTHELEMY"),
                       BM("BERMUDA"),
                       BN("BRUNEI DARUSSALAM"),
                       BO("BOLIVIA, PLURINATIONAL STATE OF"),
                       BQ("BONAIRE, SINT EUSTATIUS AND SABA"),
                       BR("BRAZIL"),
                       BS("BAHAMAS"),
                       BT("BHUTAN"),
                       BU("Burma"),
                       BV("BOUVET ISLAND"),
                       BW("BOTSWANA"),
                       BX("Benelux Trademarks and Designs Office"),
                       BY("BELARUS"),
                       BZ("BELIZE"),
                       CA("CANADA"),
                       CC("COCOS (KEELING) ISLANDS"),
                       CD("CONGO, THE DEMOCRATIC REPUBLIC OF THE"),
                       CF("CENTRAL AFRICAN REPUBLIC"),
                       CG("CONGO"),
                       CH("SWITZERLAND"),
                       CI("COTE D'IVOIRE"),
                       CK("COOK ISLANDS"),
                       CL("CHILE"),
                       CM("CAMEROON"),
                       CN("CHINA"),
                       CO("COLOMBIA"),
                       CP("Clipperton Island"),
                       CR("COSTA RICA"),
                       CS("SERBIA AND MONTENEGRO"),
                       CU("CUBA"),
                       CV("CAPE VERDE"),
                       CW("Curacao"),
                       CX("CHRISTMAS ISLAND"),
                       CY("CYPRUS"),
                       CZ("CZECH REPUBLIC"),
                       DE("GERMANY"),
                       DG("Diego Garcia"),
                       DJ("DJIBOUTI"),
                       DK("DENMARK"),
                       DM("DOMINICA"),
                       DO("DOMINICAN REPUBLIC"),
                       DY("Benin"),
                       DZ("ALGERIA"),
                       EA("Ceuta, Melilla"),
                       EC("ECUADOR"),
                       EE("ESTONIA"),
                       EF("Union of Countries under the European Community Patent Convention"),
                       EG("EGYPT"),
                       EH("WESTERN SAHARA"),
                       EM("European Trademark Office"),
                       EP("European Patent Organization"),
                       ER("ERITREA"),
                       ES("SPAIN"),
                       ET("ETHIOPIA"),
                       EU("European Union"),
                       EV("Eurasian Patent Organization"),
                       EW("Estonia"),
                       FI("FINLAND"),
                       FJ("FIJI"),
                       FK("FALKLAND ISLANDS (MALVINAS)"),
                       FL("Liechtenstein"),
                       FM("MICRONESIA, FEDERATED STATES OF"),
                       FO("FAROE ISLANDS"),
                       FR("FRANCE"),
                       FX("France, Metropolitan"),
                       GA("GABON"),
                       GB("UNITED KINGDOM"),
                       GC("Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)"),
                       GD("GRENADA"),
                       GE("GEORGIA"),
                       GF("FRENCH GUIANA"),
                       GG("GUERNSEY"),
                       GH("GHANA"),
                       GI("GIBRALTAR"),
                       GL("GREENLAND"),
                       GM("GAMBIA"),
                       GN("GUINEA"),
                       GP("GUADELOUPE"),
                       GQ("EQUATORIAL GUINEA"),
                       GR("GREECE"),
                       GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
                       GT("GUATEMALA"),
                       GU("GUAM"),
                       GW("GUINEA-BISSAU"),
                       GY("GUYANA"),
                       HK("HONG KONG"),
                       HM("HEARD ISLAND AND MCDONALD ISLANDS"),
                       HN("HONDURAS"),
                       HR("CROATIA"),
                       HT("HAITI"),
                       HU("HUNGARY"),
                       IB("International Bureau of WIPO"),
                       IC("Canary Islands"),
                       ID("INDONESIA"),
                       IE("IRELAND"),
                       IL("ISRAEL"),
                       IM("ISLE OF MAN"),
                       IN("INDIA"),
                       IO("BRITISH INDIAN OCEAN TERRITORY"),
                       IQ("IRAQ"),
                       IR("IRAN, ISLAMIC REPUBLIC OF"),
                       IS("ICELAND"),
                       IT("ITALY"),
                       JA("Jamaica"),
                       JE("JERSEY"),
                       JM("JAMAICA"),
                       JO("JORDAN"),
                       JP("JAPAN"),
                       KE("KENYA"),
                       KG("KYRGYZSTAN"),
                       KH("CAMBODIA"),
                       KI("KIRIBATI"),
                       KM("COMOROS"),
                       KN("SAINT KITTS AND NEVIS"),
                       KP("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
                       KR("KOREA, REPUBLIC OF"),
                       KW("KUWAIT"),
                       KY("CAYMAN ISLANDS"),
                       KZ("KAZAKHSTAN"),
                       LA("LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
                       LB("LEBANON"),
                       LC("SAINT LUCIA"),
                       LF("Libya Fezzan"),
                       LI("LIECHTENSTEIN"),
                       LK("SRI LANKA"),
                       LR("LIBERIA"),
                       LS("LESOTHO"),
                       LT("LITHUANIA"),
                       LU("LUXEMBOURG"),
                       LV("LATVIA"),
                       LY("LIBYA"),
                       MA("MOROCCO"),
                       MC("MONACO"),
                       MD("MOLDOVA, REPUBLIC OF"),
                       ME("MONTENEGRO"),
                       MF("SAINT MARTIN (FRENCH PART)"),
                       MG("MADAGASCAR"),
                       MH("MARSHALL ISLANDS"),
                       MK("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
                       ML("MALI"),
                       MM("MYANMAR"),
                       MN("MONGOLIA"),
                       MO("MACAO"),
                       MP("NORTHERN MARIANA ISLANDS"),
                       MQ("MARTINIQUE"),
                       MR("MAURITANIA"),
                       MS("MONTSERRAT"),
                       MT("MALTA"),
                       MU("MAURITIUS"),
                       MV("MALDIVES"),
                       MW("MALAWI"),
                       MX("MEXICO"),
                       MY("MALAYSIA"),
                       MZ("MOZAMBIQUE"),
                       NA("NAMIBIA"),
                       NC("NEW CALEDONIA"),
                       NE("NIGER"),
                       NF("NORFOLK ISLAND"),
                       NG("NIGERIA"),
                       NI("NICARAGUA"),
                       NL("NETHERLANDS"),
                       NO("NORWAY"),
                       NP("NEPAL"),
                       NR("NAURU"),
                       NT("Neutral Zone"),
                       NU("NIUE"),
                       NZ("NEW ZEALAND"),
                       OA("African Intellectual Property Organization"),
                       OM("OMAN"),
                       PA("PANAMA"),
                       PE("PERU"),
                       PF("FRENCH POLYNESIA"),
                       PG("PAPUA NEW GUINEA"),
                       PH("PHILIPPINES"),
                       PI("Philippines"),
                       PK("PAKISTAN"),
                       PL("POLAND"),
                       PM("SAINT PIERRE AND MIQUELON"),
                       PN("PITCAIRN"),
                       PR("PUERTO RICO"),
                       PS("PALESTINIAN, STATE OF"),
                       PT("PORTUGAL"),
                       PW("PALAU"),
                       PY("PARAGUAY"),
                       QA("QATAR"),
                       RA("Argentina"),
                       RB("Bolivia [cf. Botswana: identical code element]"),
                       RC("China"),
                       RE("Reunion"),
                       RH("Haiti"),
                       RI("Indonesia"),
                       RL("Lebanon"),
                       RM("Madagascar"),
                       RN("Niger"),
                       RO("ROMANIA"),
                       RP("Philippines"),
                       RS("SERBIA"),
                       RU("RUSSIAN FEDERATION"),
                       RW("RWANDA"),
                       SA("SAUDI ARABIA"),
                       SB("SOLOMON ISLANDS"),
                       SC("SEYCHELLES"),
                       SD("SUDAN"),
                       SE("SWEDEN"),
                       SF("Finland"),
                       SG("SINGAPORE"),
                       SH("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"),
                       SI("SLOVENIA"),
                       SJ("SVALBARD AND JAN MAYEN"),
                       SK("SLOVAKIA"),
                       SL("SIERRA LEONE"),
                       SM("SAN MARINO"),
                       SN("SENEGAL"),
                       SO("SOMALIA"),
                       SR("SURINAME"),
                       SS("SOUTH SUDAN"),
                       ST("SAO TOME AND PRINCIPE"),
                       SU("USSR"),
                       SV("EL SALVADOR"),
                       SX("SINT MAARTEN (DUTCH PART)"),
                       SY("SYRIAN ARAB REPUBLIC"),
                       SZ("SWAZILAND"),
                       TA("Tristan da Cunha"),
                       TC("TURKS AND CAICOS ISLANDS"),
                       TD("CHAD"),
                       TF("FRENCH SOUTHERN TERRITORIES"),
                       TG("TOGO"),
                       TH("THAILAND"),
                       TJ("TAJIKISTAN"),
                       TK("TOKELAU"),
                       TL("TIMOR-LESTE"),
                       TM("TURKMENISTAN"),
                       TN("TUNISIA"),
                       TO("TONGA"),
                       TP("East Timor"),
                       TR("TURKEY"),
                       TT("TRINIDAD AND TOBAGO"),
                       TV("TUVALU"),
                       TW("TAIWAN, PROVINCE OF CHINA"),
                       TZ("TANZANIA, UNITED REPUBLIC OF"),
                       UA("UKRAINE"),
                       UG("UGANDA"),
                       UK("United Kingdom"),
                       UM("UNITED STATES MINOR OUTLYING ISLANDS"),
                       US("UNITED STATES"),
                       UY("URUGUAY"),
                       UZ("UZBEKISTAN"),
                       VA("HOLY SEE (VATICAN CITY STATE)"),
                       VC("SAINT VINCENT AND THE GRENADINES"),
                       VE("VENEZUELA, BOLIVARIAN REPUBLIC"),
                       VG("VIRGIN ISLANDS, BRITISH"),
                       VI("VIRGIN ISLANDS, U.S."),
                       VN("VIET NAM"),
                       VU("VANUATU"),
                       WF("WALLIS AND FUTUNA"),
                       WG("Grenada"),
                       WL("Saint Lucia"),
                       WO("World Intellectual Property Organization"),
                       WS("SAMOA"),
                       WV("Saint Vincent"),
                       YE("YEMEN"),
                       YT("MAYOTTE"),
                       YU("Yugoslavia"),
                       YV("Venezuela"),
                       ZA("SOUTH AFRICA"),
                       ZM("ZAMBIA"),
                       ZR("Zaire"),
                       ZW("ZIMBABWE");

                       private String label;
Country(String _label) {
    label = _label;
}
public String getLabel() {
    return label;
}

                    }